package visao.frmproduto;

import modelo.Produto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import visao.Mensagem;

public class FrmGerenciaProduto extends javax.swing.JFrame {

    private Produto objetoproduto;

    public FrmGerenciaProduto() {
        initComponents();
        this.objetoproduto = new Produto();
        this.carregaTabela();
    }

    public void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) this.JTableProduto.getModel();
        modelo.setNumRows(0);
        ArrayList<Produto> minhaLista = objetoproduto.getMinhaLista();
        for (Produto a : minhaLista) {
            modelo.addRow(new Object[]{
                a.getId(),
                a.getProduto(),
                a.getPreco(),
                a.getUnidade(),
                a.getCategoria(),
                a.getQuantidade(),
                a.getQuantidademax(),
                a.getQuantidademin()
            });

        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableProduto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JTFproduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTFpreco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTFcategoria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTFquantidade = new javax.swing.JTextField();
        JBCancelar = new javax.swing.JButton();
        JBAlterar = new javax.swing.JButton();
        Apagar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTFquantidademax = new javax.swing.JTextField();
        JTFquantidademin = new javax.swing.JTextField();
        JBReajuste = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        JTFunidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento de Alunos");

        JTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Preço", "Unidade", "Categoria", "Quantidade", "Quantidade Máxima", "Quantidade Mínima"
            }
        ));
        JTableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableProduto);

        jLabel1.setText("Nome:");

        JTFproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFprodutoActionPerformed(evt);
            }
        });

        jLabel2.setText("Preço:");

        JTFpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFprecoActionPerformed(evt);
            }
        });

        jLabel3.setText("Categoria:");

        jLabel4.setText("Quantidade:");

        JTFquantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFquantidadeActionPerformed(evt);
            }
        });

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        JBAlterar.setText("Alterar");
        JBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAlterarActionPerformed(evt);
            }
        });

        Apagar.setText("Apagar");
        Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarActionPerformed(evt);
            }
        });

        jLabel5.setText("Quantidade Máxima:");

        jLabel6.setText("Quantidade Mínima:");

        JBReajuste.setText("Reajuste");
        JBReajuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBReajusteActionPerformed(evt);
            }
        });

        jLabel7.setText("Unidade:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 58, Short.MAX_VALUE)
                                .addComponent(JBCancelar)
                                .addGap(51, 51, 51)
                                .addComponent(JBAlterar)
                                .addGap(69, 69, 69)
                                .addComponent(JBReajuste)
                                .addGap(52, 52, 52)
                                .addComponent(Apagar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFproduto)
                                    .addComponent(JTFpreco)
                                    .addComponent(JTFunidade, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFquantidademin)
                                    .addComponent(JTFquantidademax)
                                    .addComponent(JTFquantidade)
                                    .addComponent(JTFcategoria, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTFproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTFpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JTFunidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTFcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTFquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTFquantidademax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JTFquantidademin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBCancelar)
                    .addComponent(JBAlterar)
                    .addComponent(Apagar)
                    .addComponent(JBReajuste))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFquantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFquantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFquantidadeActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAlterarActionPerformed
        try {
            int id = 0;
            String produto = "";
            double preco = 0;
            String unidade = "";
            String categoria = "";
            int quantidade = 0;
            int quantidademax = 60;
            int quantidademin = 20;

            if (this.JTFproduto.getText().length() < 2) {
                throw new Mensagem("Produto deve conter ao menos 2 caracteres.");
            } else {
                produto = this.JTFproduto.getText();
            }
            try {
                preco = Double.parseDouble(this.JTFpreco.getText().replace(",", "."));
                if (preco <= 0) {
                    throw new Mensagem("Preço deve ser maior que zero.");
                }
            } catch (NumberFormatException e) {
                throw new Mensagem("Preço deve ser um número válido (ex: 10,50).");
            }

            if (this.JTFunidade.getText().length() < 2) {
                throw new Mensagem("Unidade deve conter ao menos 2 caracteres.");
            } else {
                unidade = this.JTFunidade.getText();
            }

            if (this.JTFcategoria.getText().length() < 2) {
                throw new Mensagem("Categoria deve conter ao menos 2 caracteres.");
            } else {
                categoria = this.JTFcategoria.getText();
            }

            try {
                quantidade = Integer.parseInt(this.JTFquantidade.getText().trim());
                quantidademax = Integer.parseInt(this.JTFquantidademax.getText().trim());
                quantidademin = Integer.parseInt(this.JTFquantidademin.getText().trim());
            } catch (NumberFormatException e) {
                throw new Mensagem("Quantidades devem ser números válidos.");
            }

            if (quantidade < quantidademin) {
                throw new Mensagem("Quantidade atual não pode ser menor que a quantidade mínima.");
            }
            if (quantidade > quantidademax) {
                throw new Mensagem("Quantidade atual não pode ser maior que a quantidade máxima.");
            }
           

            if (this.JTableProduto.getSelectedRow() == -1) {
                throw new Mensagem("Primeiro selecione um produto para alterar.");
            } else {
                id = Integer.parseInt(this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 0).toString());
            }

            if (this.objetoproduto.updateProdutoBD(id, produto, preco, unidade, categoria, quantidade, quantidademax, quantidademin)) {

                this.JTFproduto.setText("");
                this.JTFpreco.setText("");
                this.JTFunidade.setText("");
                this.JTFcategoria.setText("");
                this.JTFquantidade.setText("");
                this.JTFquantidademax.setText("");
                this.JTFquantidademin.setText("");

                JOptionPane.showMessageDialog(rootPane, "Produto alterado com sucesso!");
            }
        } catch (Mensagem erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (Exception erro2) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + erro2.getMessage());
        } finally {
            carregaTabela();
        }


    }//GEN-LAST:event_JBAlterarActionPerformed

    private void JTFprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFprodutoActionPerformed

    private void JTFprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFprecoActionPerformed

    private void JTableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableProdutoMouseClicked
        if (this.JTableProduto.getSelectedRow() != -1) {

            try {

                String produto = this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 1).toString();
                String preco = this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 2).toString();
                String unidade = this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 3).toString();
                String categoria = this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 4).toString();
                String quantidade = this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 5).toString();
                String quantidademax = this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 6).toString();
                String quantidademin = this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 7).toString();

                this.JTFproduto.setText(produto);
                this.JTFpreco.setText(preco);
                this.JTFunidade.setText(unidade);
                this.JTFcategoria.setText(categoria);
                this.JTFquantidade.setText(quantidade);
                this.JTFquantidademax.setText(quantidademax);
                this.JTFquantidademin.setText(quantidademin);

            } catch (Exception e) {
                System.out.println("Erro ao selecionar item: " + e.getMessage());
                JOptionPane.showMessageDialog(this, "Erro ao carregar dados do produto selecionado");
                JOptionPane.showMessageDialog(this, "Erro ao carregar preço: " + e.getMessage());
            }

        }
    }//GEN-LAST:event_JTableProdutoMouseClicked

    private void ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarActionPerformed
        try {
            int id = 0;
            if (this.JTableProduto.getSelectedRow() == -1) {
                throw new Mensagem("Primeiro Selecione um Produto para APAGAR");
            } else {
                id = Integer.parseInt(this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 0).toString());
            }
            int respostaUsuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja apagar esse Produto?");
            if (respostaUsuario == 0) {
                if (this.objetoproduto.deleteProdutoBD(id)) {
                    this.JTFproduto.setText("");
                    this.JTFpreco.setText("");
                    this.JTFunidade.setText("");
                    this.JTFcategoria.setText("");
                    this.JTFquantidade.setText("");
                    this.JTFquantidademax.setText("");
                    this.JTFquantidademin.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Produto Apagado com sucesso!");
                }
            }
            System.out.println(this.objetoproduto.getMinhaLista().toString());
        } catch (Mensagem erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            carregaTabela();
        }
    }//GEN-LAST:event_ApagarActionPerformed

    private void JBReajusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBReajusteActionPerformed
        try {
            if (this.JTableProduto.getSelectedRow() == -1) {
                throw new Mensagem("Primeiro selecione um produto para reajustar.");
            }

            int id = Integer.parseInt(this.JTableProduto.getValueAt(this.JTableProduto.getSelectedRow(), 0).toString());
            Produto produto = objetoproduto.carregaProduto(id);
            int precoAtual = (int) produto.getPreco();

            String input = JOptionPane.showInputDialog(this,
                    "Digite o percentual de reajuste para " + produto.getProduto()
                    + "\nPreço atual: R$" + precoAtual);

            if (input != null && !input.trim().isEmpty()) {
                try {
                    double percentual = Double.parseDouble(input.trim());
                    int novoPreco = (int) Math.round(precoAtual * (1 + percentual / 100.0));

                    if (objetoproduto.updatePrecoBD(id, novoPreco)) {
                        JOptionPane.showMessageDialog(this,
                                "Preço atualizado de R$" + precoAtual
                                + " para R$" + novoPreco);
                        carregaTabela();
                    } else {
                        throw new Mensagem("Falha ao atualizar o preço no banco de dados.");
                    }
                } catch (NumberFormatException e) {
                    throw new Mensagem("Informe um percentual válido (ex: 10 para 10%).");
                }
            }
        } catch (Mensagem e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }


    }//GEN-LAST:event_JBReajusteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGerenciaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apagar;
    private javax.swing.JButton JBAlterar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBReajuste;
    private javax.swing.JTextField JTFcategoria;
    private javax.swing.JTextField JTFpreco;
    private javax.swing.JTextField JTFproduto;
    private javax.swing.JTextField JTFquantidade;
    private javax.swing.JTextField JTFquantidademax;
    private javax.swing.JTextField JTFquantidademin;
    private javax.swing.JTextField JTFunidade;
    private javax.swing.JTable JTableProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
