
package visao.frmcategoria;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Categoria;
import visao.Mensagem;


public class FrmGerenciaCategoria extends javax.swing.JFrame {
private Categoria objetocategoria;

    public FrmGerenciaCategoria() {
        initComponents();
        this.objetocategoria = new Categoria();
        this.carregaTabela();
    }
    public void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) this.JTableGerenciaCategoria.getModel();
        modelo.setNumRows(0);
        ArrayList<Categoria> minhaLista = objetocategoria.getMinhaLista();
        for (Categoria c : minhaLista) {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getEmbalagem(),
                c.getTamanho()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTableGerenciaCategoria = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JTFNomeGerencia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JCBEmbalagemGerencia = new javax.swing.JComboBox<>();
        JCBTamanhoGerencia = new javax.swing.JComboBox<>();
        JBAlternar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        JBApagar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTableGerenciaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Embalagem", "Tamanho"
            }
        ));
        JTableGerenciaCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableGerenciaCategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableGerenciaCategoria);

        jLabel1.setText("Nome:");

        jLabel2.setText("Embalagem:");

        jLabel3.setText("Tamanho:");

        JCBEmbalagemGerencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plastico", "Lata", "Vidro" }));

        JCBTamanhoGerencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeno", "Medio", "Grande" }));

        JBAlternar.setText("Alternar");
        JBAlternar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAlternarActionPerformed(evt);
            }
        });

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        JBApagar.setText("Apagar");
        JBApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBApagarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 0, 24)); // NOI18N
        jLabel4.setText("Gerencia Categoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(JTFNomeGerencia)
                                .addComponent(jLabel2)
                                .addComponent(JCBEmbalagemGerencia, 0, 121, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JCBTamanhoGerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(JBCancelar)
                                        .addGap(33, 33, 33)))
                                .addComponent(JBAlternar)
                                .addGap(36, 36, 36)
                                .addComponent(JBApagar))
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel4)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTFNomeGerencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(JCBEmbalagemGerencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(JCBTamanhoGerencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAlternar)
                    .addComponent(JBCancelar)
                    .addComponent(JBApagar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTableGerenciaCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableGerenciaCategoriaMouseClicked
if (this.JTableGerenciaCategoria.getSelectedRow() != -1) {
            try {
                String nome = this.JTableGerenciaCategoria.getValueAt(this.JTableGerenciaCategoria.getSelectedRow(), 1).toString();
                String embalagem = this.JTableGerenciaCategoria.getValueAt(this.JTableGerenciaCategoria.getSelectedRow(), 2).toString();
                String tamanho = this.JTableGerenciaCategoria.getValueAt(this.JTableGerenciaCategoria.getSelectedRow(), 3).toString();

                this.JTFNomeGerencia.setText(nome);
                this.JCBEmbalagemGerencia.setSelectedItem(embalagem);
                this.JCBTamanhoGerencia.setSelectedItem(tamanho);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao carregar dados da categoria selecionada");
            }
        }
        
    }//GEN-LAST:event_JTableGerenciaCategoriaMouseClicked

    private void JBAlternarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAlternarActionPerformed
   try{
        int id = 0;
            String nome = "";
            String embalagem = "";
            String tamanho = "";

            if (this.JTFNomeGerencia.getText().length() < 2) {
                throw new Mensagem("Nome deve conter ao menos 2 caracteres.");
            } else {
                nome = this.JTFNomeGerencia.getText();
            }
            if (this.JCBEmbalagemGerencia.getSelectedIndex() <= 0) {
                throw new Mensagem("Selecione um tipo de embalagem válido.");
            } else {
                embalagem = this.JCBEmbalagemGerencia.getSelectedItem().toString();
            }

            if (this.JCBTamanhoGerencia.getSelectedIndex() <= 0) {
                throw new Mensagem("Selecione um tamanho válido.");
            } else {
                tamanho = this.JCBTamanhoGerencia.getSelectedItem().toString();
            }
            if (this.JTableGerenciaCategoria.getSelectedRow() == -1) {
                throw new Mensagem("Primeiro selecione uma categoria para alterar.");
            } else {
                id = Integer.parseInt(this.JTableGerenciaCategoria.getValueAt(this.JTableGerenciaCategoria.getSelectedRow(), 0).toString());
            }

            if (this.objetocategoria.updateCategoriaBD(id, nome, embalagem, tamanho)) {
                this.JTFNomeGerencia.setText("");
                this.JCBEmbalagemGerencia.setSelectedIndex(0);
                this.JCBTamanhoGerencia.setSelectedIndex(0);
                JOptionPane.showMessageDialog(rootPane, "Categoria alterada com sucesso!");
            }
        } catch (Mensagem erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (Exception erro2) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + erro2.getMessage());
        } finally {
            carregaTabela();
   }  
        

    }//GEN-LAST:event_JBAlternarActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
this.dispose();       
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JBApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBApagarActionPerformed
try {
            int id = 0;
            if (this.JTableGerenciaCategoria.getSelectedRow() == -1) {
                throw new Mensagem("Primeiro Selecione uma Categoria para APAGAR");
            } else {
                id = Integer.parseInt(this.JTableGerenciaCategoria.getValueAt(this.JTableGerenciaCategoria.getSelectedRow(), 0).toString());
            }
            int respostaUsuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja apagar esta Categoria?");
            if (respostaUsuario == 0) {
                if (this.objetocategoria.deleteCategoriaBD(id)) {
                    this.JTFNomeGerencia.setText("");
                    this.JCBEmbalagemGerencia.setSelectedIndex(0);
                    this.JCBTamanhoGerencia.setSelectedIndex(0);
                    JOptionPane.showMessageDialog(rootPane, "Categoria Apagada com sucesso!");
                }
            }
        } catch (Mensagem erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            carregaTabela();
        }
    
    }//GEN-LAST:event_JBApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGerenciaCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAlternar;
    private javax.swing.JButton JBApagar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JComboBox<String> JCBEmbalagemGerencia;
    private javax.swing.JComboBox<String> JCBTamanhoGerencia;
    private javax.swing.JTextField JTFNomeGerencia;
    private javax.swing.JTable JTableGerenciaCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
