
package visao;



import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Produto;



public class FrmAdicionarSubtrairProduto extends javax.swing.JFrame {

    private Produto objetoproduto;

    public FrmAdicionarSubtrairProduto() {
        initComponents();
        this.objetoproduto = new Produto();
        this.carregaTabela();
        
    }
    public void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) this.JTableProduto.getModel();
        modelo.setNumRows(0);
        ArrayList<Produto> minhaLista = objetoproduto.getMinhaLista();
        for (Produto a : minhaLista) {
            modelo.addRow(new Object[]{
                a.getId(),
                a.getProduto(),
                a.getPreco(),
                a.getCategoria(),
                a.getQuantidade(),
                a.getQuantidademax(),
                a.getQuantidademin()
            });
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTableProduto = new javax.swing.JTable();
        JBAdicionar = new javax.swing.JButton();
        JBSubtrair = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Preço", "Categoria", "Quantidade", "Quantidade Máxima", "QuantidadeMínima"
            }
        ));
        JTableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableProduto);

        JBAdicionar.setText("Adicionar");
        JBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAdicionarActionPerformed(evt);
            }
        });

        JBSubtrair.setText("Subtrair");
        JBSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSubtrairActionPerformed(evt);
            }
        });

        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(JBAdicionar)
                        .addGap(44, 44, 44)
                        .addComponent(JBSubtrair)
                        .addGap(47, 47, 47)
                        .addComponent(JBCancelar)
                        .addGap(0, 134, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAdicionar)
                    .addComponent(JBSubtrair)
                    .addComponent(JBCancelar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAdicionarActionPerformed
        try {
            int linhaselecionada = JTableProduto.getSelectedRow();
            if (linhaselecionada == -1) {
                throw new Mensagem ("Selecione um produto para registrar entrada");
            }
            
            String valorID = JTableProduto.getValueAt(linhaselecionada, 0).toString();
            int id = Integer.parseInt(valorID);
            String textoAdicionar = JOptionPane.showInputDialog("Informe a quantidade adicional:");
            
            if (textoAdicionar != null && !textoAdicionar.isEmpty()) {
                int quantidadeAdicionar = Integer.parseInt(textoAdicionar);
                String mensagemResultado = objetoproduto.movimentarEstoque(id, quantidadeAdicionar, true);
                
                JOptionPane.showMessageDialog(this, mensagemResultado);
                carregaTabela();
}
            
            
            
            } catch (Mensagem erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
            } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um número válido.");
        }
    }//GEN-LAST:event_JBAdicionarActionPerformed

    private void JBSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSubtrairActionPerformed
        try {
            
            if (JTableProduto.getSelectedRow()  == -1) {
                throw new Mensagem ("Selecione um produto para registrar saída");
            }
            int linhaselecionada = JTableProduto.getSelectedRow();
            int idProduto =Integer.parseInt(JTableProduto.getValueAt(linhaselecionada, 0).toString());
            String subtrairUsuario = JOptionPane.showInputDialog("Informe a quantidade de saída:");
            if(subtrairUsuario != null && !subtrairUsuario.isEmpty()) {
                int quantidade = Integer.parseInt(subtrairUsuario);
                String mensagemRetorno = objetoproduto.movimentarEstoque(idProduto, quantidade, false);
                JOptionPane.showMessageDialog(this, mensagemRetorno);
                carregaTabela();
            }
            
} catch (Mensagem | NumberFormatException ex) {
    
    JOptionPane.showMessageDialog(this, "Erro:" + ex.getMessage());
            
            
            
        }
    }//GEN-LAST:event_JBSubtrairActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JTableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableProdutoMouseClicked
        
    }//GEN-LAST:event_JTableProdutoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdicionarSubtrairProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdicionarSubtrairProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdicionarSubtrairProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdicionarSubtrairProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdicionarSubtrairProduto().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAdicionar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBSubtrair;
    private javax.swing.JTable JTableProduto;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
