
package visao;

import visao.frmrelatorios.FrmProdutosCategoria;
import visao.frmrelatorios.FrmBalancoFinanceiro;
import visao.frmrelatorios.FrmListaPrecos;
import visao.frmproduto.FrmCadastroProduto;
import visao.frmproduto.FrmAdicionarSubtrairProduto;
import visao.frmproduto.FrmGerenciaProduto;
import visao.frmrelatorios.FrmProdutosQuantidadeMaxima;
import visao.frmrelatorios.FrmProdutosQuantidadeMinima;


public class FrmMenuPrincipal extends javax.swing.JFrame {

    
    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JBSair = new javax.swing.JButton();
        JBCadastrarProduto = new javax.swing.JButton();
        JBGerenciarProduto = new javax.swing.JButton();
        JBEntradaSaida = new javax.swing.JButton();
        JBGerenciaCategoria = new javax.swing.JButton();
        JBCadastrarCategoria = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMenuListaPrecos = new javax.swing.JMenuItem();
        JMenuBalancoFisico = new javax.swing.JMenuItem();
        JMenuProdutosMinimos = new javax.swing.JMenuItem();
        JMenuProdutoMaximo = new javax.swing.JMenuItem();
        JMenuProdutoCategoria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Aluno");

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabel1.setText("CONTROLE DE ESTOQUE");

        JBSair.setText("Sair");
        JBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSairActionPerformed(evt);
            }
        });

        JBCadastrarProduto.setText("Cadastrar Produto");
        JBCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCadastrarProdutoActionPerformed(evt);
            }
        });

        JBGerenciarProduto.setText("Gerenciar Produto");
        JBGerenciarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGerenciarProdutoActionPerformed(evt);
            }
        });

        JBEntradaSaida.setText("Movimento Estoque");
        JBEntradaSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEntradaSaidaActionPerformed(evt);
            }
        });

        JBGerenciaCategoria.setText("Gerencia Categoria");

        JBCadastrarCategoria.setText("Cadastrar Categoria");

        jMenu1.setText("Relatórios");

        JMenuListaPrecos.setText("Lista Preços");
        JMenuListaPrecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuListaPrecosActionPerformed(evt);
            }
        });
        jMenu1.add(JMenuListaPrecos);

        JMenuBalancoFisico.setText("Balanço Físico");
        JMenuBalancoFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuBalancoFisicoActionPerformed(evt);
            }
        });
        jMenu1.add(JMenuBalancoFisico);

        JMenuProdutosMinimos.setText("Produtos abaixo da quantidade mínima");
        JMenuProdutosMinimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuProdutosMinimosActionPerformed(evt);
            }
        });
        jMenu1.add(JMenuProdutosMinimos);

        JMenuProdutoMaximo.setText("Produtos abaixo da quantidade máxima");
        JMenuProdutoMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuProdutoMaximoActionPerformed(evt);
            }
        });
        jMenu1.add(JMenuProdutoMaximo);

        JMenuProdutoCategoria.setText("Produtos por categoria");
        JMenuProdutoCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuProdutoCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(JMenuProdutoCategoria);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(JBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JBGerenciarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JBCadastrarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBEntradaSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBCadastrarCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(JBGerenciaCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(JBCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(JBCadastrarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBGerenciaCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(JBEntradaSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(JBGerenciarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(JBSair)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuProdutosMinimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuProdutosMinimosActionPerformed
FrmProdutosQuantidadeMinima objeto = new FrmProdutosQuantidadeMinima();
objeto.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_JMenuProdutosMinimosActionPerformed

    private void JMenuProdutoMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuProdutoMaximoActionPerformed
       FrmProdutosQuantidadeMaxima objeto = new FrmProdutosQuantidadeMaxima();
objeto.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_JMenuProdutoMaximoActionPerformed

    private void JMenuProdutoCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuProdutoCategoriaActionPerformed
        FrmProdutosCategoria objeto = new FrmProdutosCategoria();
        objeto.setVisible(true);
    }//GEN-LAST:event_JMenuProdutoCategoriaActionPerformed

    private void JMenuListaPrecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuListaPrecosActionPerformed
        FrmListaPrecos objeto = new FrmListaPrecos();
        objeto.setVisible(true);
    }//GEN-LAST:event_JMenuListaPrecosActionPerformed

    private void JMenuBalancoFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuBalancoFisicoActionPerformed
        FrmBalancoFinanceiro objeto = new FrmBalancoFinanceiro();
        objeto.setVisible(true);
    }//GEN-LAST:event_JMenuBalancoFisicoActionPerformed

    private void JBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JBSairActionPerformed

    private void JBCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCadastrarProdutoActionPerformed
        FrmCadastroProduto objeto = new FrmCadastroProduto();
        objeto.setVisible(true);
    }//GEN-LAST:event_JBCadastrarProdutoActionPerformed

    private void JBGerenciarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGerenciarProdutoActionPerformed
        FrmGerenciaProduto objeto = new FrmGerenciaProduto();
        objeto.setVisible(true);
    }//GEN-LAST:event_JBGerenciarProdutoActionPerformed

    private void JBEntradaSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEntradaSaidaActionPerformed
        FrmAdicionarSubtrairProduto objeto = new FrmAdicionarSubtrairProduto();
        objeto.setVisible(true);
    }//GEN-LAST:event_JBEntradaSaidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCadastrarCategoria;
    private javax.swing.JButton JBCadastrarProduto;
    private javax.swing.JButton JBEntradaSaida;
    private javax.swing.JButton JBGerenciaCategoria;
    private javax.swing.JButton JBGerenciarProduto;
    private javax.swing.JButton JBSair;
    private javax.swing.JMenuItem JMenuBalancoFisico;
    private javax.swing.JMenuItem JMenuListaPrecos;
    private javax.swing.JMenuItem JMenuProdutoCategoria;
    private javax.swing.JMenuItem JMenuProdutoMaximo;
    private javax.swing.JMenuItem JMenuProdutosMinimos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
