
package visao;


public class FrmMenuPrincipal extends javax.swing.JFrame {

    
    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuCadastrarAluno = new javax.swing.JMenuItem();
        jMenuGerenciarAluno = new javax.swing.JMenuItem();
        jMenuAdicionarSubtrairProduto = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        JMenuListaPrecos = new javax.swing.JMenuItem();
        JMenuBalancoFisico = new javax.swing.JMenuItem();
        JMenuProdutosMinimos = new javax.swing.JMenuItem();
        JMenuProdutoMaximo = new javax.swing.JMenuItem();
        JMenuProdutoCategoria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Aluno");

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabel1.setText("CONTROLE DE ESTOQUE");

        jMenuArquivo.setText("Arquivo");

        jMenuCadastrarAluno.setText("CadastrarProduto");
        jMenuCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarAlunoActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuCadastrarAluno);

        jMenuGerenciarAluno.setText("GerenciarProduto");
        jMenuGerenciarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGerenciarAlunoActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuGerenciarAluno);

        jMenuAdicionarSubtrairProduto.setText("AdicionarSubtrairProduto");
        jMenuAdicionarSubtrairProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdicionarSubtrairProdutoActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuAdicionarSubtrairProduto);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuSair);

        jMenuBar1.add(jMenuArquivo);

        jMenu1.setText("Relatórios");

        JMenuListaPrecos.setText("Lista Preços");
        JMenuListaPrecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuListaPrecosActionPerformed(evt);
            }
        });
        jMenu1.add(JMenuListaPrecos);

        JMenuBalancoFisico.setText("Balanço Físico");
        JMenuBalancoFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuBalancoFisicoActionPerformed(evt);
            }
        });
        jMenu1.add(JMenuBalancoFisico);

        JMenuProdutosMinimos.setText("Produtos abaixo da quantidade mínima");
        JMenuProdutosMinimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuProdutosMinimosActionPerformed(evt);
            }
        });
        jMenu1.add(JMenuProdutosMinimos);

        JMenuProdutoMaximo.setText("Produtos abaixo da quantidade máxima");
        JMenuProdutoMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuProdutoMaximoActionPerformed(evt);
            }
        });
        jMenu1.add(JMenuProdutoMaximo);

        JMenuProdutoCategoria.setText("Produtos por categoria");
        JMenuProdutoCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuProdutoCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(JMenuProdutoCategoria);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuGerenciarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGerenciarAlunoActionPerformed
        FrmGerenciaProduto objeto = new FrmGerenciaProduto();
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuGerenciarAlunoActionPerformed

    private void jMenuCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarAlunoActionPerformed
        FrmCadastroProduto objeto = new FrmCadastroProduto();
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuCadastrarAlunoActionPerformed

    private void jMenuAdicionarSubtrairProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdicionarSubtrairProdutoActionPerformed
        FrmAdicionarSubtrairProduto objeto = new FrmAdicionarSubtrairProduto();
        objeto.setVisible(true);
    }//GEN-LAST:event_jMenuAdicionarSubtrairProdutoActionPerformed

    private void JMenuProdutosMinimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuProdutosMinimosActionPerformed
FrmProdutosQuantidadeMinima objeto = new FrmProdutosQuantidadeMinima();
objeto.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_JMenuProdutosMinimosActionPerformed

    private void JMenuProdutoMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuProdutoMaximoActionPerformed
       FrmProdutosQuantidadeMaxima objeto = new FrmProdutosQuantidadeMaxima();
objeto.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_JMenuProdutoMaximoActionPerformed

    private void JMenuProdutoCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuProdutoCategoriaActionPerformed
        FrmProdutosCategoria objeto = new FrmProdutosCategoria();
        objeto.setVisible(true);
    }//GEN-LAST:event_JMenuProdutoCategoriaActionPerformed

    private void JMenuListaPrecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuListaPrecosActionPerformed
        FrmListaPrecos objeto = new FrmListaPrecos();
        objeto.setVisible(true);
    }//GEN-LAST:event_JMenuListaPrecosActionPerformed

    private void JMenuBalancoFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuBalancoFisicoActionPerformed
        FrmBalancoFinanceiro objeto = new FrmBalancoFinanceiro();
        objeto.setVisible(true);
    }//GEN-LAST:event_JMenuBalancoFisicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuBalancoFisico;
    private javax.swing.JMenuItem JMenuListaPrecos;
    private javax.swing.JMenuItem JMenuProdutoCategoria;
    private javax.swing.JMenuItem JMenuProdutoMaximo;
    private javax.swing.JMenuItem JMenuProdutosMinimos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuAdicionarSubtrairProduto;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadastrarAluno;
    private javax.swing.JMenuItem jMenuGerenciarAluno;
    private javax.swing.JMenuItem jMenuSair;
    // End of variables declaration//GEN-END:variables
}
